SQLProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include, url
from hotel import urls as hotel_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(hotel_urls, namespace='hotel')),
    url("", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel/urls.py
from django.urls import path
from django.conf.urls import include, url
from . import views
app_name = "hotel"


urlpatterns = [
    path('', views.HomePage.as_view(), name='index'),
    path('search_hotel', views.search_hotel, name='search_hotel'),
    # path('search_room', views.search_hotel, name='search_room'),
    path("<int:pk>/", views.HotelPage.as_view(), name='detail'),
    path("<int:pk>/reservation", views.FormView.as_view(), name='reservation'),
    path("my_reservations", views.MyReservationsView.as_view(), name='my_reservations'),
]

hotel/models.py
from typing import Optional
from django.db import models
from django import forms
from customer.models import Customer, RoomReservation, User


ROOM_CHOICES =(
    ("1", "Standard single"),
    ("2", "Standard 2 beds"),
    ("3", "Standard king size bed"),
    ("4", "Premium single"),
    ("5", "Premium 2 beds"),
    ("6", "Premium king size bed"),
)

class Hotel(models.Model):
    hotel_name = models.CharField(max_length=100, unique=True, blank=False)
    address = models.CharField(max_length=100, blank=False)
    postal_code = models.CharField(max_length=100, blank=False)
    city = models.CharField(max_length=100, blank=False)
    country = models.CharField(max_length=100, blank=False)
    description = models.CharField(max_length=500, blank=True)
    stars = models.IntegerField(blank=False)
    hotel_image=models.ImageField(upload_to="media", height_field=None, width_field=None, max_length=None)

    def __str__(self):
        return "Hotel No: "+ str(self.id) + " - " + str(self.hotel_name)

class Room(models.Model):

    ROOM_CHOICES =(
    ("1", "Standard single"),
    ("2", "Standard 2 beds"),
    ("3", "Standard king size bed"),
    ("4", "Premium single"),
    ("5", "Premium 2 beds"),
    ("6", "Premium king size bed"),
    )


    hotel = models.ForeignKey(Hotel, related_name='rooms', on_delete=models.CASCADE)
    room_number = models.IntegerField(blank=False)
    room_type = models.CharField(max_length = 30, choices=ROOM_CHOICES, default='1')
    availability = models.BooleanField(default=False)
    price_per_night = models.IntegerField(blank=False)
    description = models.CharField(max_length=500, blank=True)
    room_image = models.ImageField(upload_to="media", height_field=None, width_field=None, max_length=None, default='static/images/no.jpg')
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)
    reservation = models.ForeignKey(RoomReservation, blank=True, null=True, on_delete=models.SET_NULL)
    

    def __str__(self):
        return "Room No: "+ str(self.room_number) + " from hotel: " + str(self.hotel.hotel_name)


class Bar(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    number_of_seats = models.IntegerField(blank=False)
    number_of_employees = models.IntegerField(blank=False)

    def __str__(self):
        return "Bar No: "+ str(self.id) + " from hotel: " + str(self.hotel.hotel_name)


class Restaurant(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    number_of_tables = models.IntegerField(blank=False)
    number_of_seats = models.IntegerField(blank=False)
    stars = models.IntegerField(blank=False)
    kitchen_type = models.CharField(max_length=100, blank=False)

    def __str__(self):
        return str(self.kitchen_type) + " Restaurant No: "+ str(self.id) + " from hotel: " + str(self.hotel.hotel_name)


class Team(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    department = models.CharField(max_length=100, blank=True)
    number_of_employees = models.IntegerField(blank=False)

    def __str__(self):
        return "Working team no: "+ str(self.id) + " from hotel - " + str(self.hotel.hotel_name)


class Employee(models.Model):
    first_name = models.CharField(max_length=100, blank=False)
    last_name = models.CharField(max_length=100, blank=False)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    salary = models.DecimalField(blank=False, max_digits=10, decimal_places=2)
    date_of_employment = models.DateTimeField(auto_now_add=True, blank=False)

    def __str__(self):
        return "Employee no: "+ str(self.id) + " - " + str(self.first_name) + " " + str(self.last_name)
    

hotel/forms.py
from .models import *
from django import forms
from customer.models import *
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from hotel.models import *

class DateInput(forms.DateInput):
    input_type = 'date'

class ReservationForm(forms.ModelForm):

    arrival_date = forms.DateField(widget=DateInput(format="%d/%m/%Y"))
    departure_date = forms.DateField(widget=DateInput(format="%d/%m/%Y"))

    class Meta:
        model = RoomReservation
        fields = ('arrival_date', 'departure_date', 'number_of_adults', 'number_of_children')

        widgets = {
            'number_of_adults': forms.TextInput(attrs={'class': 'form-control'}),
            'number_of_children': forms.TextInput(attrs={'class': 'form-control'}),
        }


class CustomerForm(forms.ModelForm):
    
    class Meta:
        model = Customer
        fields = ('telephone_number','passport_number','address','city','postal_code','country')

class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

hotel/views.py
from django.views.generic import TemplateView, ListView, DetailView, UpdateView
from django.views.generic.edit import CreateView, FormView
from django.contrib.auth.forms import UserChangeForm
from .models import Hotel, Room
from django.contrib.auth.mixins import LoginRequiredMixin
from customer.models import *
from .forms import ReservationForm, CustomerForm, UserForm
from django.http import Http404
from django.shortcuts import render
from django.contrib import messages


# def get_children_recursive(parent_category):
#     children = parent_category.children.all()  # This depends on adding related_name to Category
#     for child in children:
#         children += get_children_recursive(child)
#     return children

class HomePage(TemplateView):
    http_method_names = ['get']
    template_name = 'hotel/homepage.html'
    model = Hotel

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)


    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        hotels = Hotel.objects.all().order_by('id')
        context['hotels'] = hotels
        return context


class HotelPage(ListView):
    http_method_names = ['get']
    template_name = 'hotel/rooms.html'
    model = Room
    slug_field = 'id'
    slug_url_kwarg = 'id'

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)


    def get_queryset(self):
        hotels = []
        hotel = Hotel.objects.get(id=self.kwargs['pk'])
        hotels.append(hotel)
        return hotels[0].rooms.all()
        
        

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        rooms = self.get_queryset()
        rooms_new = rooms.filter(availability=True)
        context['rooms'] = rooms_new
        return context



class FormView(FormView):
    template_name = 'hotel/reservation.html'
    success_url = '/'

    def get_object(self):
        try:
            obj = Room.objects.get(id=self.kwargs['pk'])
        except Room.DoesNotExist:
            raise Http404('Question not found!')
        return obj

    def get_customer(self):
        customer = Customer.objects.get(user=self.request.user)
        return customer

    def get_context_data(self, **kwargs):
        kwargs['room'] = self.get_object()
        if 'reservation_form' not in kwargs:
            kwargs['reservation_form'] = ReservationForm()
        if 'customer_form' not in kwargs:
            kwargs['customer_form'] = CustomerForm()
        if 'user_form' not in kwargs:
            kwargs['user_form'] = UserForm()

        return kwargs

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.get_context_data())


    def post(self, request, *args, **kwargs):
        reservation_form = ReservationForm(request.POST)
        customer_form = CustomerForm(request.POST, instance=self.get_customer())
        user_form = UserForm(request.POST, instance=self.request.user)
        ctxt = {}
        # print(reservation_form.is_valid())
        # print(customer_form.is_valid())
        # print(user_form.is_valid())
        #customer_form.user = self.request.user
        if reservation_form.is_valid() and customer_form.is_valid() and user_form.is_valid():
            reservation_form.save()
            user_form.save()
            customer_form.save()
            room = self.get_object()
            room.availability = False
            room.reservation = reservation_form.save()
            room.user = user_form.save()
            room.save()

            
            return super().form_valid(reservation_form)
        else:
            ctxt['reservation_form'] = reservation_form
            ctxt['customer_form'] = customer_form
            ctxt['user_form'] = user_form

        return render(request, self.template_name, self.get_context_data(**ctxt))


class MyReservationsView(ListView):
    http_method_names = ['get']
    template_name = 'hotel/my_reservations.html'
    model = Room

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        rooms = Room.objects.all().filter(user=self.request.user)
        total_price_list = []
        print(rooms)
        for room in rooms:
            if room.reservation.bill != None:
                price = room.price_per_night
                restaurant = room.reservation.bill.restauration_bill
                bar = room.reservation.bill.bar_bill
                first_date = room.reservation.arrival_date
                second_date = room.reservation.departure_date
                days = (second_date - first_date).days
                total = (days * price) + restaurant + bar
                total_price_list.append([room.room_number, total])
        context['rooms'] = rooms
        print(total_price_list)
        context['total_price_list'] = total_price_list
        return context


def search_hotel(request):
    if request.method == 'POST':
        searched = request.POST['searched']
        hotels = Hotel.objects.filter(hotel_name__contains=searched)
        return render(request, 'hotel/search_hotel.html', {'searched': searched, 'hotels': hotels})

hotel/templates/hotel/homepage.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}Home{% endblock %}


{% block body %}
    {% for hotel in hotels %}
        <div class="container mx-auto my-5">

            <div class="relative rounded-lg flex flex-col md:flex-row items-center md:shadow-xl md:h-72 mx-2">
                
                <div class="z-0 order-1 md:order-2 relative w-full md:w-2/5 h-80 md:h-full overflow-hidden rounded-lg md:rounded-none md:rounded-r-lg">
                    {% thumbnail hotel.hotel_image "1920" crop="center" as im %}
                    <div class="absolute inset-0 w-full h-full object-fill object-center bg-blue-400 bg-opacity-30 bg-cover bg-bottom" style="background-image: url('{{ im.url }}'); background-blend-mode: multiply;"></div>
                    {% endthumbnail %}
                    <div class="md:hidden absolute inset-0 h-full p-6 pb-6 flex flex-col-reverse justify-start items-start bg-gradient-to-b from-transparent via-transparent to-gray-900">
                        <h3 class="w-full font-bold text-2xl text-white leading-tight mb-2">{{hotel.hotel_name}}</h3>
                        <h4 class="w-full text-xl text-gray-100 leading-tight">{{hotel.stars}} stars</h4>
                    </div>
                    <svg class="hidden md:block absolute inset-y-0 h-full w-24 fill-current text-white -ml-12" viewBox="0 0 100 100" preserveAspectRatio="none">
                        <polygon points="50,0 100,0 50,100 0,100" />
                    </svg>
                </div>

                <div class="z-10 order-2 md:order-1 w-full h-full md:w-3/5 flex items-center -mt-6 md:mt-0">
                    <div class="p-8 md:pr-18 md:pl-14 md:py-12 mx-2 md:mx-0 h-full bg-white rounded-lg md:rounded-none md:rounded-l-lg shadow-xl md:shadow-none">
                        <h4 class="hidden md:block text-xl text-gray-400">{{hotel.stars}} stars</h4>
                        <h3 class="hidden md:block font-bold text-2xl text-gray-700">{{hotel.hotel_name}}</h3>
                        <p class="text-gray-600 text-justify">{{hotel.address}} {{hotel.city}} {{hotel.postal_code}} {{hotel.country}}</p>
                        <p class="text-gray-600 text-justify">{{hotel.description}}</p>
                        <a class="flex items-baseline mt-3 text-blue-600 hover:text-blue-900 focus:text-blue-900" href="{% url 'hotel:detail' hotel.id%}">
                            <span>Check available rooms</span>
                            <span class="text-xs ml-1">&#x279c;</span>
                        </a>
                    </div>
                </div>

            </div>
        </div>
    {% endfor %}
{% endblock %}

hotel/templates/hotel/my_reservations.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}My Reservations{% endblock %}

{% block body %}
    {% if user.is_authenticated %}
        {% csrf_token %}
            {% for room in rooms %}
            <section class="text-blueGray-700 bg-white mt-20">
                <div class="container flex flex-col items-center px-5 py-16 mx-auto md:flex-row lg:px-28">
                    <div class="flex flex-col items-start mb-16 text-left lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 md:mb-0">
                        <h2 class="mb-8 text-xs font-semibold tracking-widest text-black uppercase title-font"> {{room.reservation.arrival_date}} - {{room.reservation.departure_date}}</h2>
                        <h1 class="mb-8 text-2xl font-black tracking-tighter text-black md:text-5xl title-font"> {{room.get_room_type_display}} </h1>
                        {% for total_price in total_price_list %}
                            {% if total_price.0 == room.room_number %}
                            <p class="mb-8 text-base leading-relaxed text-left text-blueGray-600 "> {{room.reservation.number_of_adults}} adults and {{room.reservation.number_of_children}} kids</p>
                            {% endif %}
                        {% endfor %}
                        
                        <div class="flex flex-col justify-center lg:flex-row">
                            <button class="flex items-center px-6 py-2 mt-auto font-semibold text-white transition duration-500 ease-in-out transform bg-blue-600 rounded-lg hover:bg-blue-700 focus:shadow-outline focus:outline-none focus:ring-2 ring-offset-current ring-offset-2">Pay for your room</button>
                            {% for total_price in total_price_list %}
                                {% if total_price.0 == room.room_number %}
                                    <p class="mt-2 text-sm text-left text-blueGray-600 md:ml-6 md:mt-0">Total price: {{total_price.1}}$<br class="hidden lg:block">
                                {% endif %}
                            {% endfor %}
                            <a href="#" class="inline-flex items-center font-semibold text-blue-600 md:mb-2 lg:mb-0 hover:text-black " title="read more">Paid: {{room.reservation.bill.payment_state}} Check your bill » </a>
                            </p>
                        </div>
                    </div>
                    <div class="w-full lg:w-1/3 lg:max-w-lg md:w-1/2">
                        {% thumbnail room.room_image "700x600" crop="center" as im %}
                            <div class="object-cover object-center rounded-lg " style="background-image: url('{{ im.url }}'); width: 700px; height: 400px;"></div>
                        {% endthumbnail %}
                        <!-- <img class="object-cover object-center rounded-lg " alt="hero" src="https://dummyimage.com/720x600/F3F4F7/8693ac"> -->
                    </div>
                </div>
            </section>
            {% endfor %}


    {% endif %}
{% endblock %}

hotel/templates/hotel/reservation.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}User Form{% endblock %}

{% block body %}
<div class="mx-auto container items-center px-5 py-12 lg:px-20">
    {% if user.is_authenticated %}
    <form method="post" class="flex flex-col w-full p-10 px-8 pt-6 mx-auto my-6 mb-4 transition duration-500 ease-in-out transform bg-white border rounded-lg lg:w-1/2 ">
      <section class="flex flex-col w-full h-full p-1 overflow-auto">
        {% csrf_token %}
        {{ user_form.as_p }}
        <!-- {{ customer_form.telephone_number }}
        {{ customer_form.passport_number }} -->
        {{ reservation_form.as_p }}
        {{ customer_form.as_p }}
        <input class="p-2 pl-5 pr-5 bg-transparent border-2 border-blue-500 text-blue-500 text-lg rounded-lg hover:bg-blue-500 hover:text-gray-100 focus:border-4 focus:border-blue-300" type="submit">
      </div>
    </form>
    {% else %}
    <h1>YOU NEED TO LOG IN</h1>
    {% endif %}


{% endblock %}

hotel/templates/hotel/rooms.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}Rooms{% endblock %}


{% block body %}
    {% for room in rooms %}
    <main class="flex items-center p-10 pb-2 pt-2 w-full h-full bg-white">
        <div class="border-t border-b pt-16 grid grid-cols-2 gap-8">
            <div class="flex flex-col justify-start">
                <div class="flex flex-col w-full object-cover h-5/6 justify-items-start border rounded-lg overflow-hidden"
                    style="min-heigth:320px">
                    {% thumbnail room.room_image "750x350" crop="center" as im %}
                    <div class="w-full h-full object-cover" style="background-image: url('{{ im.url }}'); width: 750; height: 400px;"></div>
                    {% endthumbnail %}
                    <!-- <img class="w-full h-full object-cover" src='https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80' alt='nike shoes' > -->
                </div>
                </div>
                <div class="flex flex-col">
                    <div class="flex flex-col gap-4">
                        <h1 class="capitalize text-4xl font-extrabold">Room number: {{room.room_number}} {{room.get_room_type_display}}</h1>
                        <h2 class="text-3xl">${{room.price_per_night}}</h2>
                        <p class="text-lg text-gray-500	">{{room.description}}</p>
                        <div class="flex items-center gap-4 my-6 cursor-pointer ">
                            <div class="bg-blue-600 px-5 py-3 text-white rounded-lg w-2/4 text-center">
                                <a href="{% url 'hotel:reservation' room.id%}">Make reservation</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </main>
    {% endfor %}
{% endblock %}

hotel/templates/hotel/search_hotel.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}Your hotel search results{% endblock %}


{% block body %}
{% if searched %}
    {% for hotel in hotels %}
    <div class="container mx-auto my-5">

        <div class="relative rounded-lg flex flex-col md:flex-row items-center md:shadow-xl md:h-72 mx-2">
            
            <div class="z-0 order-1 md:order-2 relative w-full md:w-2/5 h-80 md:h-full overflow-hidden rounded-lg md:rounded-none md:rounded-r-lg">
                {% thumbnail hotel.hotel_image "1920" crop="center" as im %}
                <div class="absolute inset-0 w-full h-full object-fill object-center bg-blue-400 bg-opacity-30 bg-cover bg-bottom" style="background-image: url('{{ im.url }}'); background-blend-mode: multiply;"></div>
                {% endthumbnail %}
                <div class="md:hidden absolute inset-0 h-full p-6 pb-6 flex flex-col-reverse justify-start items-start bg-gradient-to-b from-transparent via-transparent to-gray-900">
                    <h3 class="w-full font-bold text-2xl text-white leading-tight mb-2">{{hotel.hotel_name}}</h3>
                    <h4 class="w-full text-xl text-gray-100 leading-tight">{{hotel.stars}} stars</h4>
                </div>
                <svg class="hidden md:block absolute inset-y-0 h-full w-24 fill-current text-white -ml-12" viewBox="0 0 100 100" preserveAspectRatio="none">
                    <polygon points="50,0 100,0 50,100 0,100" />
                </svg>
            </div>

            <div class="z-10 order-2 md:order-1 w-full h-full md:w-3/5 flex items-center -mt-6 md:mt-0">
                <div class="p-8 md:pr-18 md:pl-14 md:py-12 mx-2 md:mx-0 h-full bg-white rounded-lg md:rounded-none md:rounded-l-lg shadow-xl md:shadow-none">
                    <h4 class="hidden md:block text-xl text-gray-400">{{hotel.stars}} stars</h4>
                    <h3 class="hidden md:block font-bold text-2xl text-gray-700">{{hotel.hotel_name}}</h3>
                    <p class="text-gray-600 text-justify">{{hotel.address}} {{hotel.city}} {{hotel.postal_code}} {{hotel.country}}</p>
                    <p class="text-gray-600 text-justify">{{hotel.description}}</p>
                    <a class="flex items-baseline mt-3 text-blue-600 hover:text-blue-900 focus:text-blue-900" href="{% url 'hotel:detail' hotel.id%}">
                        <span>Check available rooms</span>
                        <span class="text-xs ml-1">&#x279c;</span>
                    </a>
                </div>
            </div>

        </div>
    </div>
    {% endfor %}
{% else %}
    <h1>empty input</h1>
{% endif %}
{% endblock %}

hotel/templates/hotel/search_room.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}Your hotel search results{% endblock %}


{% block body %}
{% if searched %}
    {% for room in rooms %}
    <main class="flex items-center p-10 pb-2 pt-2 w-full h-full bg-white">
        <div class="border-t border-b pt-16 grid grid-cols-2 gap-8">
            <div class="flex flex-col justify-start">
                <div class="flex flex-col w-full object-cover h-5/6 justify-items-start border rounded-lg overflow-hidden"
                    style="min-heigth:320px">
                    {% thumbnail room.room_image "750x350" crop="center" as im %}
                    <div class="w-full h-full object-cover" style="background-image: url('{{ im.url }}'); width: 750; height: 400px;"></div>
                    {% endthumbnail %}
                    <!-- <img class="w-full h-full object-cover" src='https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80' alt='nike shoes' > -->
                </div>
                </div>
                <div class="flex flex-col">
                    <div class="flex flex-col gap-4">
                        <h1 class="capitalize text-4xl font-extrabold">Room number: {{room.room_number}} {{room.get_room_type_display}}</h1>
                        <h2 class="text-3xl">${{room.price_per_night}}</h2>
                        <p class="text-lg text-gray-500	">{{room.description}}</p>
                        <div class="flex items-center gap-4 my-6 cursor-pointer ">
                            <div class="bg-blue-600 px-5 py-3 text-white rounded-lg w-2/4 text-center">
                                <a href="{% url 'hotel:reservation' room.id%}">Make reservation</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </main>
    {% endfor %}
{% else %}
    <h1>empty input</h1>
{% endif %}
{% endblock %}