SQLProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include, url
from hotel import urls as hotel_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(hotel_urls, namespace='hotel')),
    url("", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel/urls.py
from django.urls import path
from django.conf.urls import include, url
from . import views
app_name = "hotel"


urlpatterns = [
    path('', views.HomePage.as_view(), name='index'),
    path('search_hotel', views.search_hotel, name='search_hotel'),
    # path('search_room', views.search_hotel, name='search_room'),
    path("<int:pk>/", views.HotelPage.as_view(), name='detail'),
    path("<int:pk>/reservation", views.FormView.as_view(), name='reservation'),
    path("my_reservations", views.MyReservationsView.as_view(), name='my_reservations'),
]

SQLProject/templates/base.html
{% load static %}
{% load thumbnail %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Base title{% endblock %}</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css" />
    <link rel="stylesheet" href="https://demos.creative-tim.com/notus-js/assets/styles/tailwind.css">
    <link rel="stylesheet" href="https://demos.creative-tim.com/notus-js/assets/vendor/@fortawesome/fontawesome-free/css/all.min.css">
    

</head>

<body>
    <div class="min-h-screen bg-white">
        
        <style>
            @media only screen and (min-width: 768px){
                .parent:hover .child {
                    opacity:1;
                    height:auto;
                    overflow:none;
                    transform: translateY(0);
                }
                .child {
                    opacity:0;
                    height:0;
                    overflow:hidden;
                    transform: translateY(-10%);
                }
            }
            
        </style>
        
            <nav class="flex px-4 border-b md:shadow-lg items-center relative">
                <div class="text-lg font-bold md:py-0 py-4">
                    Hotel Booking App
                </div>
                <ul class="md:px-2 ml-auto md:flex md:space-x-2 absolute md:relative top-full left-0 right-0">
                    {% if request.get_full_path == '/' %}
                    <li>
                        <div class="pt-2 relative mx-auto text-gray-600">
                            <form class="d-flex" method=POST action="{% url 'hotel:search_hotel' %}">
                                {% csrf_token %}
                        
                                <input class="form-control me-2" type="search" placeholder="Search Hotels" aria-label="Search" name="searched">
                                <button class="btn btn-outline-secondary" type="submit">Search</button>
                              </form>
                        </div>
                    </li>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                    <li>
                        <a href="#" class="flex md:inline-flex p-4 items-center hover:bg-gray-50">
                            <span>Hi {{user.username}}!</span>
                        </a>
                    </li>
                    {% endif %}
                    <li>
                        <a href="/" class="flex md:inline-flex p-4 items-center hover:bg-gray-50">
                            <span>Home</span>
                        </a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li>
                        <a href="{% url 'hotel:my_reservations' %}" class="flex md:inline-flex p-4 items-center hover:bg-gray-50">
                            <span>My reservations</span>
                        </a>
                    </li>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                    <li>
                        <a href="{% url 'account_logout' %}" class="flex md:inline-flex p-4 items-center hover:bg-gray-50">
                            <span>Logout</span>
                        </a>
                    </li>
                    {% else %}
                    <li>
                        <a href="{% url 'account_login' %}" class="flex md:inline-flex p-4 items-center hover:bg-gray-50">
                            <span>Login</span>
                        </a>
                    </li>
                    {% endif %}
                </ul>
                <div class="ml-auto md:hidden text-gray-500 cursor-pointer">
                    <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 fill-current" viewBox="0 0 24 24"><path d="M24 20.188l-8.315-8.209 8.2-8.282-3.697-3.697-8.212 8.318-8.31-8.203-3.666 3.666 8.321 8.24-8.206 8.313 3.666 3.666 8.237-8.318 8.285 8.203z"/></svg>
                </div>
            </nav>
            {% block body %}

            {% endblock %}
        </div>
</body>
</html>